// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileList():Promise<Array<string>>;

export function GetTabId():Promise<string>;

export function GetTabLocation():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Version():Promise<string>;
