// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileList() {
  return window['go']['main']['App']['GetFileList']();
}

export function GetHomeFolderFileList() {
  return window['go']['main']['App']['GetHomeFolderFileList']();
}

export function GetTabId() {
  return window['go']['main']['App']['GetTabId']();
}

export function GetTabLocation() {
  return window['go']['main']['App']['GetTabLocation']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NavigateToHomeFolderSubFolder(arg1) {
  return window['go']['main']['App']['NavigateToHomeFolderSubFolder'](arg1);
}

export function NavigateToSubFolder(arg1) {
  return window['go']['main']['App']['NavigateToSubFolder'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
