// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFileList():Promise<Array<main.FileResult>>;

export function GetHomeFolderFileList():Promise<Array<string>>;

export function GetTabId():Promise<string>;

export function GetTabLocation():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function NavigateToHomeFolderSubFolder(arg1:string):Promise<void>;

export function NavigateToSubFolder(arg1:string):Promise<void>;

export function Version():Promise<string>;
